name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (use requirements.txt if non-empty)
        run: |
          if [ -s requirements.txt ]; then
            echo "Installing from requirements.txt"
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt missing or empty — installing minimal deps"
            python -m pip install playwright pytest pytest-playwright pytest-html
          fi

      - name: Install Playwright system dependencies
        run: npx playwright install-deps

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Run tests and generate HTML report
        run: |
          mkdir -p reports
          xvfb-run pytest -q --junitxml=reports/junit.xml --html=reports/report.html --self-contained-html

      - name: Upload test report (junit.xml)
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/junit.xml
          if-no-files-found: ignore

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html
          if-no-files-found: ignore