name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPORT_DIR: reports

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || python -m pip install playwright pytest pytest-playwright pytest-html

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          browsers: 'all'

      - name: Run tests & generate HTML report
        run: |
          mkdir -p $REPORT_DIR
          pytest --html=$REPORT_DIR/report.html --self-contained-html --junitxml=$REPORT_DIR/junit.xml || true

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: ${{ env.REPORT_DIR }}/report.html
          if-no-files-found: error

      - name: Upload junit xml
        uses: actions/upload-artifact@v4
        with:
          name: pytest-junit
          path: ${{ env.REPORT_DIR }}/junit.xml
          if-no-files-found: ignore
