name: CI

# triggers: push and pull_request run the test job automatically.
# Use "Run workflow" (workflow_dispatch) in GitHub UI to manually choose environment and deploy.
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'qa'
        type: choice
        # options must be provided as a YAML sequence (below)
        options:
          - qa
          - test
          - prod

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (use requirements.txt if non-empty)
        run: |
          if [ -s requirements.txt ]; then
            echo "Installing from requirements.txt"
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt missing or empty — installing minimal deps"
            python -m pip install playwright pytest pytest-playwright pytest-html
          fi

      - name: Install Playwright system dependencies
        run: npx playwright install-deps

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Run tests and generate HTML report
        run: |
          mkdir -p reports
          xvfb-run pytest -q --junitxml=reports/junit.xml --html=reports/report.html --self-contained-html

      - name: Upload test report (junit.xml)
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/junit.xml
          if-no-files-found: ignore

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html
          if-no-files-found: ignore

  deploy:
    # Ensure deploy waits for tests to complete
    needs: test
    runs-on: ubuntu-latest
    # Only run deploy when workflow was manually triggered (workflow_dispatch)
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Confirm selected environment
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
          echo "::set-output name=env::${{ github.event.inputs.environment }}"
        # Note: set-output is deprecated in some contexts but used here for clarity. Not strictly required.

      - name: Deploy to selected environment
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "Deploying to ${ENV} ..."
          # Replace the following with your real deploy commands
          if [ -x ./deploy.sh ]; then
            ./deploy.sh "${ENV}"
          else
            echo "deploy.sh not found or not executable — simulate deploy for ${ENV}"
          fi

      - name: Notify deployment success
        run: echo "Deployment finished for ${{ github.event.inputs.environment }}"
